/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppVaultRouteImport } from './routes/_app.app.vault'
import { Route as AppAppTreasuryRouteImport } from './routes/_app.app.treasury'
import { Route as AppAppTasksRouteImport } from './routes/_app.app.tasks'
import { Route as AppAppSovereignRouteImport } from './routes/_app.app.sovereign'
import { Route as AppAppSettingsRouteImport } from './routes/_app.app.settings'
import { Route as AppAppRhRouteImport } from './routes/_app.app.rh'
import { Route as AppAppProjectsRouteImport } from './routes/_app.app.projects'
import { Route as AppAppProfileRouteImport } from './routes/_app.app.profile'
import { Route as AppAppMarketingRouteImport } from './routes/_app.app.marketing'
import { Route as AppAppLeadsRouteImport } from './routes/_app.app.leads'
import { Route as AppAppKnowledgeRouteImport } from './routes/_app.app.knowledge'
import { Route as AppAppJobDescriptionsRouteImport } from './routes/_app.app.job-descriptions'
import { Route as AppAppInvoicesRouteImport } from './routes/_app.app.invoices'
import { Route as AppAppIdeasRouteImport } from './routes/_app.app.ideas'
import { Route as AppAppDashboardRouteImport } from './routes/_app.app.dashboard'
import { Route as AppAppCalendarRouteImport } from './routes/_app.app.calendar'
import { Route as AppAppBusinessRouteImport } from './routes/_app.app.business'
import { Route as AppAppAgentsRouteImport } from './routes/_app.app.agents'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppVaultRoute = AppAppVaultRouteImport.update({
  id: '/app/vault',
  path: '/app/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTreasuryRoute = AppAppTreasuryRouteImport.update({
  id: '/app/treasury',
  path: '/app/treasury',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTasksRoute = AppAppTasksRouteImport.update({
  id: '/app/tasks',
  path: '/app/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSovereignRoute = AppAppSovereignRouteImport.update({
  id: '/app/sovereign',
  path: '/app/sovereign',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSettingsRoute = AppAppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRhRoute = AppAppRhRouteImport.update({
  id: '/app/rh',
  path: '/app/rh',
  getParentRoute: () => AppRoute,
} as any)
const AppAppProjectsRoute = AppAppProjectsRouteImport.update({
  id: '/app/projects',
  path: '/app/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppAppProfileRoute = AppAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAppMarketingRoute = AppAppMarketingRouteImport.update({
  id: '/app/marketing',
  path: '/app/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppAppLeadsRoute = AppAppLeadsRouteImport.update({
  id: '/app/leads',
  path: '/app/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppAppKnowledgeRoute = AppAppKnowledgeRouteImport.update({
  id: '/app/knowledge',
  path: '/app/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppAppJobDescriptionsRoute = AppAppJobDescriptionsRouteImport.update({
  id: '/app/job-descriptions',
  path: '/app/job-descriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppAppInvoicesRoute = AppAppInvoicesRouteImport.update({
  id: '/app/invoices',
  path: '/app/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppAppIdeasRoute = AppAppIdeasRouteImport.update({
  id: '/app/ideas',
  path: '/app/ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppAppDashboardRoute = AppAppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAppCalendarRoute = AppAppCalendarRouteImport.update({
  id: '/app/calendar',
  path: '/app/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAppBusinessRoute = AppAppBusinessRouteImport.update({
  id: '/app/business',
  path: '/app/business',
  getParentRoute: () => AppRoute,
} as any)
const AppAppAgentsRoute = AppAppAgentsRouteImport.update({
  id: '/app/agents',
  path: '/app/agents',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/agents': typeof AppAppAgentsRoute
  '/app/business': typeof AppAppBusinessRoute
  '/app/calendar': typeof AppAppCalendarRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/app/ideas': typeof AppAppIdeasRoute
  '/app/invoices': typeof AppAppInvoicesRoute
  '/app/job-descriptions': typeof AppAppJobDescriptionsRoute
  '/app/knowledge': typeof AppAppKnowledgeRoute
  '/app/leads': typeof AppAppLeadsRoute
  '/app/marketing': typeof AppAppMarketingRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app/projects': typeof AppAppProjectsRoute
  '/app/rh': typeof AppAppRhRoute
  '/app/settings': typeof AppAppSettingsRoute
  '/app/sovereign': typeof AppAppSovereignRoute
  '/app/tasks': typeof AppAppTasksRoute
  '/app/treasury': typeof AppAppTreasuryRoute
  '/app/vault': typeof AppAppVaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/agents': typeof AppAppAgentsRoute
  '/app/business': typeof AppAppBusinessRoute
  '/app/calendar': typeof AppAppCalendarRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/app/ideas': typeof AppAppIdeasRoute
  '/app/invoices': typeof AppAppInvoicesRoute
  '/app/job-descriptions': typeof AppAppJobDescriptionsRoute
  '/app/knowledge': typeof AppAppKnowledgeRoute
  '/app/leads': typeof AppAppLeadsRoute
  '/app/marketing': typeof AppAppMarketingRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app/projects': typeof AppAppProjectsRoute
  '/app/rh': typeof AppAppRhRoute
  '/app/settings': typeof AppAppSettingsRoute
  '/app/sovereign': typeof AppAppSovereignRoute
  '/app/tasks': typeof AppAppTasksRoute
  '/app/treasury': typeof AppAppTreasuryRoute
  '/app/vault': typeof AppAppVaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/app/agents': typeof AppAppAgentsRoute
  '/_app/app/business': typeof AppAppBusinessRoute
  '/_app/app/calendar': typeof AppAppCalendarRoute
  '/_app/app/dashboard': typeof AppAppDashboardRoute
  '/_app/app/ideas': typeof AppAppIdeasRoute
  '/_app/app/invoices': typeof AppAppInvoicesRoute
  '/_app/app/job-descriptions': typeof AppAppJobDescriptionsRoute
  '/_app/app/knowledge': typeof AppAppKnowledgeRoute
  '/_app/app/leads': typeof AppAppLeadsRoute
  '/_app/app/marketing': typeof AppAppMarketingRoute
  '/_app/app/profile': typeof AppAppProfileRoute
  '/_app/app/projects': typeof AppAppProjectsRoute
  '/_app/app/rh': typeof AppAppRhRoute
  '/_app/app/settings': typeof AppAppSettingsRoute
  '/_app/app/sovereign': typeof AppAppSovereignRoute
  '/_app/app/tasks': typeof AppAppTasksRoute
  '/_app/app/treasury': typeof AppAppTreasuryRoute
  '/_app/app/vault': typeof AppAppVaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app/agents'
    | '/app/business'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/ideas'
    | '/app/invoices'
    | '/app/job-descriptions'
    | '/app/knowledge'
    | '/app/leads'
    | '/app/marketing'
    | '/app/profile'
    | '/app/projects'
    | '/app/rh'
    | '/app/settings'
    | '/app/sovereign'
    | '/app/tasks'
    | '/app/treasury'
    | '/app/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/agents'
    | '/app/business'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/ideas'
    | '/app/invoices'
    | '/app/job-descriptions'
    | '/app/knowledge'
    | '/app/leads'
    | '/app/marketing'
    | '/app/profile'
    | '/app/projects'
    | '/app/rh'
    | '/app/settings'
    | '/app/sovereign'
    | '/app/tasks'
    | '/app/treasury'
    | '/app/vault'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/app/agents'
    | '/_app/app/business'
    | '/_app/app/calendar'
    | '/_app/app/dashboard'
    | '/_app/app/ideas'
    | '/_app/app/invoices'
    | '/_app/app/job-descriptions'
    | '/_app/app/knowledge'
    | '/_app/app/leads'
    | '/_app/app/marketing'
    | '/_app/app/profile'
    | '/_app/app/projects'
    | '/_app/app/rh'
    | '/_app/app/settings'
    | '/_app/app/sovereign'
    | '/_app/app/tasks'
    | '/_app/app/treasury'
    | '/_app/app/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/vault': {
      id: '/_app/app/vault'
      path: '/app/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AppAppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/treasury': {
      id: '/_app/app/treasury'
      path: '/app/treasury'
      fullPath: '/app/treasury'
      preLoaderRoute: typeof AppAppTreasuryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/tasks': {
      id: '/_app/app/tasks'
      path: '/app/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppAppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/sovereign': {
      id: '/_app/app/sovereign'
      path: '/app/sovereign'
      fullPath: '/app/sovereign'
      preLoaderRoute: typeof AppAppSovereignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/settings': {
      id: '/_app/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/rh': {
      id: '/_app/app/rh'
      path: '/app/rh'
      fullPath: '/app/rh'
      preLoaderRoute: typeof AppAppRhRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/projects': {
      id: '/_app/app/projects'
      path: '/app/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppAppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/profile': {
      id: '/_app/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/marketing': {
      id: '/_app/app/marketing'
      path: '/app/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppAppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/leads': {
      id: '/_app/app/leads'
      path: '/app/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppAppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/knowledge': {
      id: '/_app/app/knowledge'
      path: '/app/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppAppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/job-descriptions': {
      id: '/_app/app/job-descriptions'
      path: '/app/job-descriptions'
      fullPath: '/app/job-descriptions'
      preLoaderRoute: typeof AppAppJobDescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/invoices': {
      id: '/_app/app/invoices'
      path: '/app/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppAppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/ideas': {
      id: '/_app/app/ideas'
      path: '/app/ideas'
      fullPath: '/app/ideas'
      preLoaderRoute: typeof AppAppIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/dashboard': {
      id: '/_app/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppAppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/calendar': {
      id: '/_app/app/calendar'
      path: '/app/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppAppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/business': {
      id: '/_app/app/business'
      path: '/app/business'
      fullPath: '/app/business'
      preLoaderRoute: typeof AppAppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/agents': {
      id: '/_app/app/agents'
      path: '/app/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppAgentsRoute: typeof AppAppAgentsRoute
  AppAppBusinessRoute: typeof AppAppBusinessRoute
  AppAppCalendarRoute: typeof AppAppCalendarRoute
  AppAppDashboardRoute: typeof AppAppDashboardRoute
  AppAppIdeasRoute: typeof AppAppIdeasRoute
  AppAppInvoicesRoute: typeof AppAppInvoicesRoute
  AppAppJobDescriptionsRoute: typeof AppAppJobDescriptionsRoute
  AppAppKnowledgeRoute: typeof AppAppKnowledgeRoute
  AppAppLeadsRoute: typeof AppAppLeadsRoute
  AppAppMarketingRoute: typeof AppAppMarketingRoute
  AppAppProfileRoute: typeof AppAppProfileRoute
  AppAppProjectsRoute: typeof AppAppProjectsRoute
  AppAppRhRoute: typeof AppAppRhRoute
  AppAppSettingsRoute: typeof AppAppSettingsRoute
  AppAppSovereignRoute: typeof AppAppSovereignRoute
  AppAppTasksRoute: typeof AppAppTasksRoute
  AppAppTreasuryRoute: typeof AppAppTreasuryRoute
  AppAppVaultRoute: typeof AppAppVaultRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppAgentsRoute: AppAppAgentsRoute,
  AppAppBusinessRoute: AppAppBusinessRoute,
  AppAppCalendarRoute: AppAppCalendarRoute,
  AppAppDashboardRoute: AppAppDashboardRoute,
  AppAppIdeasRoute: AppAppIdeasRoute,
  AppAppInvoicesRoute: AppAppInvoicesRoute,
  AppAppJobDescriptionsRoute: AppAppJobDescriptionsRoute,
  AppAppKnowledgeRoute: AppAppKnowledgeRoute,
  AppAppLeadsRoute: AppAppLeadsRoute,
  AppAppMarketingRoute: AppAppMarketingRoute,
  AppAppProfileRoute: AppAppProfileRoute,
  AppAppProjectsRoute: AppAppProjectsRoute,
  AppAppRhRoute: AppAppRhRoute,
  AppAppSettingsRoute: AppAppSettingsRoute,
  AppAppSovereignRoute: AppAppSovereignRoute,
  AppAppTasksRoute: AppAppTasksRoute,
  AppAppTreasuryRoute: AppAppTreasuryRoute,
  AppAppVaultRoute: AppAppVaultRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
